services:
  - type: web
    name: ai-resume-matcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDb7E5UxQR3Qy_52239bUsgMOliBROIIUc
